export const HEADLESS_VIEWS = [
  "login",
  "signup",
  "password",
  "forgot-password",
  "forgot-password-sent",
  "password-reset",
  "email-otp",
  "email-otp-verify",
  "email-otp-signup-verify",
  "magic-link",
  "magic-link-sent",
  "phone-otp",
  "phone-otp-verify",
  "phone-otp-signup",
  "phone-otp-signup-verify",
  "invite",
  "invite-login",
  "invite-email-otp-verify",
  "invite-accepted",
  "device",
  "device-approve",
  "device-approved",
  "device-denied",
  "mfa",
  "mfa-enroll",
  "organization",
  "consent",
  "logged-out",
] as const;

export type HeadlessView = (typeof HEADLESS_VIEWS)[number];

export const HEADLESS_ACTION_PATHS = [
  "/start",
  "/invitations/resolve",
  "/device/resolve",
  "/device/approve",
  "/device/deny",
  "/consent/approve",
  "/consent/deny",
  "/identify",
  "/password/login",
  "/password/forgot",
  "/password/reset",
  "/email-otp/start",
  "/email-otp/verify",
  "/magic-link/start",
  "/magic-link/complete",
  "/signup/email-otp/start",
  "/signup/email-otp/verify",
  "/invitations/signup",
  "/phone-otp/start",
  "/phone-otp/verify",
  "/signup/phone-otp/start",
  "/signup/phone-otp/verify",
  "/signup",
  "/organization/select",
  "/mfa/verify",
  "/mfa/totp/enroll/start",
  "/mfa/totp/enroll/verify",
  "/provider/start",
] as const;

export const HEADLESS_GET_PATHS = ["/requests/{requestId}"] as const;

export const HEADLESS_ACTION_RESULT_TYPES = ["view", "redirect"] as const;

export const HEADLESS_VIEW_MODEL_FIELDS = [
  "view",
  "authBasePath",
  "headlessApiBasePath",
  "settings",
  "requestId",
  "clientId",
  "clientName",
  "email",
  "displayName",
  "error",
  "info",
  "fieldErrors",
  "challengeToken",
  "signupToken",
  "pendingToken",
  "organizationSelection",
  "providers",
  "invitation",
  "uiContext",
  "deviceAuthorization",
  "phoneNumber",
  "mfaToken",
  "requiresMfaEnrollment",
  "mfaMethods",
  "totpEnrollment",
  "scope",
  "omittedOpenId",
  "consentToken",
  "consentScopes",
] as const;

export const HEADLESS_ACTION_RESULT_FIELDS = [
  "type",
  "redirectUrl",
  "viewModel",
] as const;
