// Generates public/env.js, the runtime configuration index.html loads before
// the application bundle. SQLOS_API_URL lets the Aspire AppHost (or the e2e
// tests) point a second copy of this app at an API on another port without a
// rebuild-time define. Runs before dev, start, and build.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const apiUrl = (process.env.SQLOS_API_URL ?? "http://localhost:5062").trim().replace(/\/+$/, "");
const target = path.join(root, "public", "env.js");

fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(
  target,
  `// Generated by scripts/write-env.mjs — do not edit.\nwindow.SQLOS_API_URL = ${JSON.stringify(apiUrl)};\n`,
);
console.log(`public/env.js: SQLOS_API_URL=${apiUrl}`);
