using System.Linq.Expressions;
using System.Reflection;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using SqlOS.Database;
using SqlOS.Fga.Configuration;
using SqlOS.Fga.Extensions;
using SqlOS.Fga.Interfaces;
using SqlOS.Fga.Models;
using SqlOS.Fga.Services;

namespace SqlOS.Tests.Fga;

/// <summary>
/// Pins the FGA read path to SqlOS 7.2.1: the <c>fn_IsResourceAccessible</c> script each provider
/// installs and the expression <c>BuildFilterAsync</c> composes into host queries. The files under
/// <c>Fga/ReadPathPin</c> were generated by this code running against the <c>v7.2.1</c> tag
/// (25fb3f0). The FGA write model must never change them (docs/architecture/domain-model.md §1).
/// </summary>
[TestClass]
public sealed class FgaReadPathPinTests
{
    [TestMethod]
    [DataRow("SqlServer", "default")]
    [DataRow("SqlServer", "custom")]
    [DataRow("PostgreSql", "default")]
    [DataRow("PostgreSql", "custom")]
    public void Fn_is_resource_accessible_scripts_match_7_2_1(string provider, string options)
    {
        var actual = ReadPathPin.FunctionSql(provider, options);

        Assert.AreEqual(Snapshot($"fn_IsResourceAccessible.{provider}.{options}.sql"), Normalize(actual));
    }

    [TestMethod]
    public async Task Build_filter_expression_shape_matches_7_2_1()
    {
        var actual = await ReadPathPin.DescribeFiltersAsync();

        Assert.AreEqual(Snapshot("BuildFilterAsync.expression.txt"), Normalize(actual));
    }

    private static string Snapshot(string name)
        => Normalize(File.ReadAllText(Path.Combine(RepositoryRoot(), "tests", "SqlOS.Tests", "Fga", "ReadPathPin", name)));

    private static string Normalize(string text) => text.Replace("\r\n", "\n", StringComparison.Ordinal);

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null && !File.Exists(Path.Combine(directory.FullName, "SqlOS.sln")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("Could not find the repository root (SqlOS.sln).");
    }
}

/// <summary>Builds the read-path artifacts the pin compares, with the same inputs on every version.</summary>
internal static class ReadPathPin
{
    public static string FunctionSql(string provider, string options)
    {
        ISqlOSDatabaseProvider database = provider switch
        {
            "SqlServer" => SqlServerDatabaseProvider.Instance,
            "PostgreSql" => PostgreSqlDatabaseProvider.Instance,
            _ => throw new ArgumentOutOfRangeException(nameof(provider), provider, null)
        };

        return database.BuildIsResourceAccessibleFunctionSql(options == "custom" ? CustomOptions() : new SqlOSFgaOptions());
    }

    /// <summary>
    /// The filter for a user who belongs to one active and one inactive group, then the filters for
    /// an unknown subject and an unknown permission.
    /// </summary>
    public static async Task<string> DescribeFiltersAsync()
    {
        await using var context = new ReadPathPinContext(
            new DbContextOptionsBuilder<ReadPathPinContext>()
                .UseInMemoryDatabase($"ReadPathPin_{Guid.NewGuid():N}")
                .Options);
        await ReadPathPinData.SeedAsync(context);
        var service = new SqlOSFgaAuthService(context, Options.Create(new SqlOSFgaOptions()), NullLogger<SqlOSFgaAuthService>.Instance);

        var text = new StringBuilder();
        text.AppendLine("# user with an active and an inactive group");
        ExpressionShape.Write(text, await service.BuildFilterAsync<PinnedEntity>("pin-user", "pin.read"), 0);
        text.AppendLine("# unknown subject");
        ExpressionShape.Write(text, await service.BuildFilterAsync<PinnedEntity>("no-such-subject", "pin.read"), 0);
        text.AppendLine("# unknown permission");
        ExpressionShape.Write(text, await service.BuildFilterAsync<PinnedEntity>("pin-user", "no.such.permission"), 0);
        return text.ToString();
    }

    private static SqlOSFgaOptions CustomOptions()
    {
        var options = new SqlOSFgaOptions
        {
            Schema = "authz",
            MaxResourceHierarchyDepth = 25
        };
        var tables = options.TableNames;
        tables.Subjects = "AppSubjects";
        tables.UserGroups = "AppUserGroups";
        tables.Resources = "AppResources";
        tables.Grants = "AppGrants";
        tables.Permissions = "AppPermissions";
        tables.RolePermissions = "AppRolePermissions";
        tables.ServiceAccounts = "AppServiceAccounts";
        tables.Users = "AppUsers";
        tables.Agents = "AppAgents";
        return options;
    }
}

/// <summary>A canonical, line-per-node description of an expression tree, with captured values.</summary>
internal static class ExpressionShape
{
    public static void Write(StringBuilder text, Expression? expression, int depth)
    {
        var indent = new string(' ', depth * 2);
        switch (expression)
        {
            case null:
                text.Append(indent).AppendLine("null");
                break;
            case LambdaExpression lambda:
                text.Append(indent).Append("Lambda ").AppendLine(Name(lambda.Type));
                foreach (var parameter in lambda.Parameters)
                {
                    text.Append(indent).Append("  param ").Append(parameter.Name).Append(": ").AppendLine(Name(parameter.Type));
                }

                Write(text, lambda.Body, depth + 1);
                break;
            case MethodCallExpression call:
                text.Append(indent).Append("Call ").Append(Name(call.Method.DeclaringType)).Append('.').Append(call.Method.Name);
                if (call.Method.IsGenericMethod)
                {
                    text.Append('<').Append(string.Join(",", call.Method.GetGenericArguments().Select(Name))).Append('>');
                }

                text.Append('(').Append(string.Join(", ", call.Method.GetParameters().Select(parameter => Name(parameter.ParameterType))))
                    .Append(") -> ").AppendLine(Name(call.Type));
                if (call.Object != null)
                {
                    text.Append(indent).AppendLine("  on");
                    Write(text, call.Object, depth + 2);
                }

                foreach (var argument in call.Arguments)
                {
                    Write(text, argument, depth + 1);
                }

                break;
            case MemberExpression member:
                text.Append(indent).Append("Member ").Append(member.Member.MemberType).Append(' ')
                    .Append(Name(member.Member.DeclaringType)).Append('.').Append(member.Member.Name).Append(": ").Append(Name(member.Type));
                if (member is { Expression: ConstantExpression owner, Member: FieldInfo field })
                {
                    text.Append(" = ").Append(field.GetValue(owner.Value));
                }

                text.AppendLine();
                Write(text, member.Expression, depth + 1);
                break;
            case ConstantExpression constant:
                text.Append(indent).Append("Constant ").Append(Name(constant.Type));
                if (constant.Value is bool or string or int)
                {
                    text.Append(" = ").Append(constant.Value);
                }

                text.AppendLine();
                break;
            case ParameterExpression parameter:
                text.Append(indent).Append("Parameter ").Append(parameter.Name).Append(": ").AppendLine(Name(parameter.Type));
                break;
            default:
                text.Append(indent).Append(expression.NodeType).Append(' ').AppendLine(Name(expression.Type));
                break;
        }
    }

    private static string Name(Type? type)
    {
        if (type == null)
        {
            return "?";
        }

        var name = type.IsNested ? $"{Name(type.DeclaringType)}+{type.Name}" : $"{type.Namespace}.{type.Name}";
        return type.IsGenericType
            ? $"{name[..name.IndexOf('`')]}<{string.Join(",", type.GetGenericArguments().Select(Name))}>"
            : name;
    }
}

public sealed class PinnedEntity : IHasResourceId
{
    public string ResourceId { get; set; } = string.Empty;
}

public sealed class ReadPathPinContext : DbContext, ISqlOSFgaDbContext
{
    public ReadPathPinContext(DbContextOptions<ReadPathPinContext> options)
        : base(options)
    {
    }

    public IQueryable<SqlOSFgaAccessibleResource> IsResourceAccessible(string resourceId, string subjectIds, string permissionId)
        => FromExpression(() => IsResourceAccessible(resourceId, subjectIds, permissionId));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplySqlOSFgaModel();
        modelBuilder.Entity<PinnedEntity>().HasKey(entity => entity.ResourceId);
    }
}
