// public/env.js (generated by scripts/write-env.mjs from SQLOS_API_URL) is
// loaded by index.html before the bundle, so the AppHost can point a second
// copy of this app at an API on another port. Without it the default applies.
const runtime = globalThis as { SQLOS_API_URL?: string };

export const environment = {
  apiUrl: runtime.SQLOS_API_URL ?? 'http://localhost:5062',
  clientId: 'example-angular',
};
