using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using SqlOS.AuditLogs;
using SqlOS.AuthServer.Configuration;
using SqlOS.AuthServer.Contracts;
using SqlOS.AuthServer.Interfaces;
using SqlOS.AuthServer.Models;
using SqlOS.Fga.Models;

namespace SqlOS.AuthServer.Services;

public sealed class SqlOSScimException : InvalidOperationException
{
    public SqlOSScimException(int statusCode, string message, string? scimType = null)
        : base(message)
    {
        StatusCode = statusCode;
        ScimType = scimType;
    }

    public int StatusCode { get; }
    public string? ScimType { get; }
}

public sealed class SqlOSScimService
{
    private const string UserSchema = "urn:ietf:params:scim:schemas:core:2.0:User";
    private const string GroupSchema = "urn:ietf:params:scim:schemas:core:2.0:Group";
    private const string ListResponseSchema = "urn:ietf:params:scim:api:messages:2.0:ListResponse";
    private const string PatchOpSchema = "urn:ietf:params:scim:api:messages:2.0:PatchOp";
    private const string ErrorSchema = "urn:ietf:params:scim:api:messages:2.0:Error";

    private readonly ISqlOSAuthServerDbContext _context;
    private readonly SqlOSAuthServerOptions _options;
    private readonly SqlOSCryptoService _cryptoService;

    public SqlOSScimService(
        ISqlOSAuthServerDbContext context,
        IOptions<SqlOSAuthServerOptions> options,
        SqlOSCryptoService cryptoService)
    {
        _context = context;
        _options = options.Value;
        _cryptoService = cryptoService;
    }

    public static JsonObject CreateError(int statusCode, string message, string? scimType = null)
    {
        var error = new JsonObject
        {
            ["schemas"] = new JsonArray(ErrorSchema),
            ["status"] = statusCode.ToString(),
            ["detail"] = message
        };
        if (!string.IsNullOrWhiteSpace(scimType))
        {
            error["scimType"] = scimType;
        }

        return error;
    }

    public async Task<SqlOSScimConnection> AuthenticateAsync(HttpContext context, CancellationToken cancellationToken = default)
    {
        if (!_options.EnableScim)
        {
            throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM is not enabled.");
        }

        var header = context.Request.Headers.Authorization.ToString();
        if (!header.StartsWith("Bearer ", StringComparison.OrdinalIgnoreCase))
        {
            throw new SqlOSScimException(StatusCodes.Status401Unauthorized, "SCIM bearer token is required.");
        }

        var token = header["Bearer ".Length..].Trim();
        if (string.IsNullOrWhiteSpace(token))
        {
            throw new SqlOSScimException(StatusCodes.Status401Unauthorized, "SCIM bearer token is required.");
        }

        var tokenHash = _cryptoService.HashToken(token);
        var connection = await _context.Set<SqlOSScimConnection>()
            .Include(x => x.Organization)
            .FirstOrDefaultAsync(x => x.TokenHash == tokenHash && x.IsEnabled, cancellationToken);

        if (connection?.Organization == null || !connection.Organization.IsActive)
        {
            throw new SqlOSScimException(StatusCodes.Status401Unauthorized, "Invalid SCIM bearer token.");
        }

        connection.TokenLastUsedAt = DateTime.UtcNow;
        await _context.SaveChangesAsync(cancellationToken);
        return connection;
    }

    public JsonObject GetServiceProviderConfig()
        => new()
        {
            ["schemas"] = new JsonArray("urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig"),
            ["patch"] = new JsonObject { ["supported"] = true },
            ["bulk"] = new JsonObject { ["supported"] = false },
            ["filter"] = new JsonObject { ["supported"] = true, ["maxResults"] = 200 },
            ["changePassword"] = new JsonObject { ["supported"] = false },
            ["sort"] = new JsonObject { ["supported"] = false },
            ["etag"] = new JsonObject { ["supported"] = false },
            ["authenticationSchemes"] = new JsonArray(new JsonObject
            {
                ["name"] = "OAuth Bearer Token",
                ["description"] = "Organization-scoped SCIM bearer token generated by SqlOS.",
                ["type"] = "oauthbearertoken",
                ["primary"] = true
            })
        };

    public JsonObject GetResourceTypes()
        => ListResponse(new JsonArray(
            new JsonObject
            {
                ["id"] = "User",
                ["name"] = "User",
                ["endpoint"] = "/Users",
                ["schema"] = UserSchema
            },
            new JsonObject
            {
                ["id"] = "Group",
                ["name"] = "Group",
                ["endpoint"] = "/Groups",
                ["schema"] = GroupSchema
            }), 2, 1, 2);

    public JsonObject GetSchemas()
        => ListResponse(new JsonArray(
            new JsonObject
            {
                ["id"] = UserSchema,
                ["name"] = "User"
            },
            new JsonObject
            {
                ["id"] = GroupSchema,
                ["name"] = "Group"
            }), 2, 1, 2);

    public async Task<JsonObject> ListUsersAsync(SqlOSScimConnection connection, int? startIndex, int? count, string? filter, CancellationToken cancellationToken = default)
    {
        var users = await _context.Set<SqlOSMembership>()
            .AsNoTracking()
            .Include(x => x.User)
            .Where(x => x.OrganizationId == connection.OrganizationId)
            .Select(x => x.User!)
            .OrderBy(x => x.DefaultEmail ?? x.DisplayName)
            .ToListAsync(cancellationToken);

        if (!string.IsNullOrWhiteSpace(filter))
        {
            var expected = TryReadEqFilter(filter, "userName") ?? TryReadEqFilter(filter, "externalId");
            if (!string.IsNullOrWhiteSpace(expected))
            {
                users = users
                    .Where(x => string.Equals(x.DefaultEmail, expected, StringComparison.OrdinalIgnoreCase)
                        || string.Equals(x.Id, expected, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }
        }

        var total = users.Count;
        var (skip, take, resolvedStart, resolvedCount) = ResolveScimPaging(startIndex, count);
        var resources = new JsonArray();
        foreach (var user in users.Skip(skip).Take(take))
        {
            resources.Add(await ToScimUserAsync(connection, user, cancellationToken));
        }

        return ListResponse(resources, total, resolvedStart, resolvedCount);
    }

    public async Task<JsonObject> GetUserAsync(SqlOSScimConnection connection, string id, CancellationToken cancellationToken = default)
    {
        var user = await _context.Set<SqlOSUser>()
            .FirstOrDefaultAsync(x => x.Id == id, cancellationToken)
            ?? throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM user not found.");

        var membership = await _context.Set<SqlOSMembership>()
            .AnyAsync(x => x.OrganizationId == connection.OrganizationId && x.UserId == user.Id, cancellationToken);
        if (!membership)
        {
            throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM user not found.");
        }

        return await ToScimUserAsync(connection, user, cancellationToken);
    }

    public async Task<JsonObject> UpsertUserAsync(SqlOSScimConnection connection, JsonObject payload, bool replace, CancellationToken cancellationToken = default)
    {
        var request = ParseUser(payload);
        var externalId = NormalizeScimExternalId(request.ExternalId, request.UserName);
        var now = DateTime.UtcNow;
        var link = await FindExternalLinkAsync(connection.Id, "User", externalId, cancellationToken);
        SqlOSUser? user = null;

        if (link != null)
        {
            user = await _context.Set<SqlOSUser>().FirstOrDefaultAsync(x => x.Id == link.EntityId, cancellationToken);
        }

        if (user == null && !string.IsNullOrWhiteSpace(request.Email))
        {
            var normalizedEmail = SqlOSAdminService.NormalizeEmail(request.Email);
            var email = await _context.Set<SqlOSUserEmail>()
                .Include(x => x.User)
                .FirstOrDefaultAsync(x => x.NormalizedEmail == normalizedEmail, cancellationToken);
            user = email?.User;
        }

        var created = user == null;
        if (user == null)
        {
            user = new SqlOSUser
            {
                Id = _cryptoService.GenerateId("usr"),
                DisplayName = request.DisplayName,
                DefaultEmail = request.Email,
                IsActive = request.Active,
                CreatedAt = now,
                UpdatedAt = now
            };
            _context.Set<SqlOSUser>().Add(user);
        }
        else
        {
            user.DisplayName = request.DisplayName;
            user.DefaultEmail = request.Email ?? user.DefaultEmail;
            user.IsActive = request.Active;
            user.UpdatedAt = now;
        }

        if (!string.IsNullOrWhiteSpace(request.Email))
        {
            await UpsertPrimaryEmailAsync(user, request.Email, now, cancellationToken);
        }

        await UpsertMembershipAsync(connection.OrganizationId, user.Id, request.Active, now, cancellationToken);
        var fgaSubjectId = await EnsureFgaUserAsync(connection, user, now, cancellationToken);
        await UpsertExternalLinkAsync(connection.Id, "User", externalId, user.Id, fgaSubjectId, user.DisplayName, request.Active, now, cancellationToken);

        if (!request.Active)
        {
            await DeprovisionUserAccessAsync(connection, user.Id, fgaSubjectId, cancellationToken);
        }

        connection.LastSyncAt = now;
        await RecordSyncEventAsync(connection, "User", user.Id, externalId, created ? "scim.user.created" : request.Active ? "scim.user.updated" : "scim.user.deactivated", "success", null, payload, cancellationToken);
        await RecordAuditAsync(created ? "scim.user.created" : request.Active ? "scim.user.updated" : "scim.user.deactivated", connection.OrganizationId, "User", user.Id, externalId, payload, cancellationToken);
        await _context.SaveChangesAsync(cancellationToken);

        return await ToScimUserAsync(connection, user, cancellationToken);
    }

    public async Task<JsonObject> PatchUserAsync(SqlOSScimConnection connection, string id, JsonObject payload, CancellationToken cancellationToken = default)
    {
        var user = await _context.Set<SqlOSUser>()
            .FirstOrDefaultAsync(x => x.Id == id, cancellationToken)
            ?? throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM user not found.");
        var membershipExists = await _context.Set<SqlOSMembership>()
            .AnyAsync(x => x.OrganizationId == connection.OrganizationId && x.UserId == user.Id, cancellationToken);
        if (!membershipExists)
        {
            throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM user not found.");
        }
        var link = await _context.Set<SqlOSScimExternalId>()
            .AsNoTracking()
            .FirstOrDefaultAsync(x => x.ConnectionId == connection.Id && x.ResourceType == "User" && x.EntityId == user.Id, cancellationToken);

        var active = user.IsActive;
        var displayName = user.DisplayName;
        var email = user.DefaultEmail;
        foreach (var op in ReadOperations(payload))
        {
            var path = op.Path?.Trim();
            if (string.Equals(path, "active", StringComparison.OrdinalIgnoreCase))
            {
                active = op.Value?.GetValue<bool>() ?? active;
            }
            else if (string.Equals(path, "displayName", StringComparison.OrdinalIgnoreCase)
                || string.Equals(path, "name.formatted", StringComparison.OrdinalIgnoreCase))
            {
                displayName = op.Value?.GetValue<string>() ?? displayName;
            }
            else if (string.Equals(path, "userName", StringComparison.OrdinalIgnoreCase))
            {
                email = op.Value?.GetValue<string>() ?? email;
            }
        }

        var body = new JsonObject
        {
            ["externalId"] = link?.ExternalId ?? id,
            ["userName"] = email,
            ["displayName"] = displayName,
            ["active"] = active
        };
        return await UpsertUserAsync(connection, body, replace: false, cancellationToken);
    }

    public async Task DeleteUserAsync(SqlOSScimConnection connection, string id, CancellationToken cancellationToken = default)
    {
        var user = await _context.Set<SqlOSUser>()
            .FirstOrDefaultAsync(x => x.Id == id, cancellationToken)
            ?? throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM user not found.");
        var now = DateTime.UtcNow;
        var link = await _context.Set<SqlOSScimExternalId>()
            .FirstOrDefaultAsync(x => x.ConnectionId == connection.Id && x.ResourceType == "User" && x.EntityId == user.Id, cancellationToken);
        var fgaSubjectId = await FindFgaSubjectIdForUserAsync(connection.Id, user.Id, cancellationToken);
        user.IsActive = false;
        user.UpdatedAt = now;
        if (link != null)
        {
            link.IsActive = false;
            link.UpdatedAt = now;
            link.LastSyncedAt = now;
        }
        await DeprovisionUserAccessAsync(connection, user.Id, fgaSubjectId, cancellationToken);
        await RecordSyncEventAsync(connection, "User", user.Id, link?.ExternalId, "scim.user.deactivated", "success", null, null, cancellationToken);
        await RecordAuditAsync("scim.user.deactivated", connection.OrganizationId, "User", user.Id, link?.ExternalId, null, cancellationToken);
        await _context.SaveChangesAsync(cancellationToken);
    }

    public async Task<JsonObject> ListGroupsAsync(SqlOSScimConnection connection, int? startIndex, int? count, string? filter, CancellationToken cancellationToken = default)
    {
        var links = await _context.Set<SqlOSScimExternalId>()
            .AsNoTracking()
            .Where(x => x.ConnectionId == connection.Id && x.ResourceType == "Group" && x.IsActive)
            .OrderBy(x => x.DisplayName)
            .ToListAsync(cancellationToken);

        if (!string.IsNullOrWhiteSpace(filter))
        {
            var expected = TryReadEqFilter(filter, "displayName") ?? TryReadEqFilter(filter, "externalId");
            if (!string.IsNullOrWhiteSpace(expected))
            {
                links = links
                    .Where(x => string.Equals(x.DisplayName, expected, StringComparison.OrdinalIgnoreCase)
                        || string.Equals(x.ExternalId, expected, StringComparison.OrdinalIgnoreCase))
                    .ToList();
            }
        }

        var total = links.Count;
        var (skip, take, resolvedStart, resolvedCount) = ResolveScimPaging(startIndex, count);
        var resources = new JsonArray();
        foreach (var link in links.Skip(skip).Take(take))
        {
            resources.Add(await ToScimGroupAsync(connection, link.EntityId, cancellationToken));
        }

        return ListResponse(resources, total, resolvedStart, resolvedCount);
    }

    public async Task<JsonObject> GetGroupAsync(SqlOSScimConnection connection, string id, CancellationToken cancellationToken = default)
        => await ToScimGroupAsync(connection, id, cancellationToken);

    public async Task<JsonObject> UpsertGroupAsync(SqlOSScimConnection connection, JsonObject payload, bool replace, CancellationToken cancellationToken = default)
    {
        var request = ParseGroup(payload);
        var externalId = NormalizeScimExternalId(request.ExternalId, request.DisplayName);
        var now = DateTime.UtcNow;
        var link = await FindExternalLinkAsync(connection.Id, "Group", externalId, cancellationToken);
        SqlOSFgaUserGroup? group = null;

        if (link != null)
        {
            group = await _context.Set<SqlOSFgaUserGroup>()
                .FirstOrDefaultAsync(x => x.Id == link.EntityId, cancellationToken);
        }

        var created = group == null;
        if (group == null)
        {
            await EnsureFgaSubjectTypeAsync("group", "Group", cancellationToken);
            var subject = new SqlOSFgaSubject
            {
                Id = _cryptoService.GenerateId("subj"),
                SubjectTypeId = "group",
                DisplayName = request.DisplayName,
                OrganizationId = connection.OrganizationId,
                ExternalRef = externalId,
                CreatedAt = now,
                UpdatedAt = now
            };
            group = new SqlOSFgaUserGroup
            {
                Id = _cryptoService.GenerateId("grp"),
                SubjectId = subject.Id,
                Name = request.DisplayName,
                Description = "SCIM mirrored group",
                GroupType = "scim",
                CreatedAt = now,
                UpdatedAt = now
            };
            _context.Set<SqlOSFgaSubject>().Add(subject);
            _context.Set<SqlOSFgaUserGroup>().Add(group);
        }
        else
        {
            group.Name = request.DisplayName;
            group.UpdatedAt = now;
            var subject = await _context.Set<SqlOSFgaSubject>().FirstOrDefaultAsync(x => x.Id == group.SubjectId, cancellationToken);
            if (subject != null)
            {
                subject.DisplayName = request.DisplayName;
                subject.UpdatedAt = now;
            }
        }

        await UpsertExternalLinkAsync(connection.Id, "Group", externalId, group.Id, group.SubjectId, request.DisplayName, true, now, cancellationToken);
        await ReplaceGroupMembersAsync(connection, group, externalId, request.Members, cancellationToken);
        await ApplyGroupMappingsAsync(connection, group, externalId, request.DisplayName, cancellationToken);

        connection.LastSyncAt = now;
        await RecordSyncEventAsync(connection, "Group", group.Id, externalId, created ? "scim.group.created" : "scim.group.updated", "success", null, payload, cancellationToken);
        await RecordAuditAsync(created ? "scim.group.created" : "scim.group.updated", connection.OrganizationId, "Group", group.Id, externalId, payload, cancellationToken);
        await _context.SaveChangesAsync(cancellationToken);
        return await ToScimGroupAsync(connection, group.Id, cancellationToken);
    }

    public async Task<JsonObject> PatchGroupAsync(SqlOSScimConnection connection, string id, JsonObject payload, CancellationToken cancellationToken = default)
    {
        var link = await _context.Set<SqlOSScimExternalId>()
            .FirstOrDefaultAsync(x => x.ConnectionId == connection.Id && x.ResourceType == "Group" && x.EntityId == id, cancellationToken)
            ?? throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM group not found.");
        var group = await _context.Set<SqlOSFgaUserGroup>().FirstAsync(x => x.Id == id, cancellationToken);
        var members = await GetCurrentScimGroupMembersAsync(connection.Id, group.Id, cancellationToken);

        foreach (var op in ReadOperations(payload))
        {
            if (string.Equals(op.Path, "displayName", StringComparison.OrdinalIgnoreCase))
            {
                group.Name = op.Value?.GetValue<string>() ?? group.Name;
                link.DisplayName = group.Name;
            }
            else if (string.Equals(op.Path, "members", StringComparison.OrdinalIgnoreCase) || string.IsNullOrWhiteSpace(op.Path))
            {
                var values = ReadMemberValues(op.Value);
                if (string.Equals(op.Op, "remove", StringComparison.OrdinalIgnoreCase))
                {
                    members.RemoveAll(x => values.Contains(x, StringComparer.OrdinalIgnoreCase));
                }
                else
                {
                    foreach (var value in values)
                    {
                        if (!members.Contains(value, StringComparer.OrdinalIgnoreCase))
                        {
                            members.Add(value);
                        }
                    }
                }
            }
        }

        var body = new JsonObject
        {
            ["displayName"] = group.Name,
            ["externalId"] = link.ExternalId,
            ["members"] = new JsonArray(members.Select(value => new JsonObject { ["value"] = value }).ToArray<JsonNode?>())
        };
        return await UpsertGroupAsync(connection, body, replace: false, cancellationToken);
    }

    public async Task DeleteGroupAsync(SqlOSScimConnection connection, string id, CancellationToken cancellationToken = default)
    {
        var link = await _context.Set<SqlOSScimExternalId>()
            .FirstOrDefaultAsync(x => x.ConnectionId == connection.Id && x.ResourceType == "Group" && x.EntityId == id, cancellationToken)
            ?? throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM group not found.");

        var group = await _context.Set<SqlOSFgaUserGroup>().FirstOrDefaultAsync(x => x.Id == id, cancellationToken);
        if (group != null)
        {
            var memberships = await _context.Set<SqlOSFgaUserGroupMembership>()
                .Where(x => x.UserGroupId == group.Id)
                .ToListAsync(cancellationToken);
            _context.Set<SqlOSFgaUserGroupMembership>().RemoveRange(memberships);
            await RevokeManagedGrantsForGroupAsync(connection, link.ExternalId, cancellationToken);
        }

        link.IsActive = false;
        link.UpdatedAt = DateTime.UtcNow;
        await RecordSyncEventAsync(connection, "Group", id, link.ExternalId, "scim.group.deleted", "success", null, null, cancellationToken);
        await RecordAuditAsync("scim.group.deleted", connection.OrganizationId, "Group", id, link.ExternalId, null, cancellationToken);
        await _context.SaveChangesAsync(cancellationToken);
    }

    private async Task UpsertPrimaryEmailAsync(SqlOSUser user, string email, DateTime now, CancellationToken cancellationToken)
    {
        var normalized = SqlOSAdminService.NormalizeEmail(email);
        var existing = await _context.Set<SqlOSUserEmail>()
            .FirstOrDefaultAsync(x => x.NormalizedEmail == normalized, cancellationToken);
        if (existing != null && existing.UserId != user.Id)
        {
            throw new SqlOSScimException(StatusCodes.Status409Conflict, $"Email '{email}' already belongs to another user.", "uniqueness");
        }

        if (existing == null)
        {
            existing = new SqlOSUserEmail
            {
                Id = _cryptoService.GenerateId("eml"),
                UserId = user.Id,
                CreatedAt = now
            };
            _context.Set<SqlOSUserEmail>().Add(existing);
        }

        existing.Email = email;
        existing.NormalizedEmail = normalized;
        existing.IsPrimary = true;
        existing.IsVerified = true;
        existing.VerifiedAt ??= now;
    }

    private async Task UpsertMembershipAsync(string organizationId, string userId, bool active, DateTime now, CancellationToken cancellationToken)
    {
        var membership = await _context.Set<SqlOSMembership>()
            .FirstOrDefaultAsync(x => x.OrganizationId == organizationId && x.UserId == userId, cancellationToken);
        if (membership == null)
        {
            membership = new SqlOSMembership
            {
                OrganizationId = organizationId,
                UserId = userId,
                Role = "member",
                CreatedAt = now
            };
            _context.Set<SqlOSMembership>().Add(membership);
        }

        membership.IsActive = active;
    }

    private async Task<string> EnsureFgaUserAsync(SqlOSScimConnection connection, SqlOSUser user, DateTime now, CancellationToken cancellationToken)
    {
        var existingSubjectId = await FindFgaSubjectIdForUserAsync(connection.Id, user.Id, cancellationToken);
        if (!string.IsNullOrWhiteSpace(existingSubjectId))
        {
            var subject = await _context.Set<SqlOSFgaSubject>().FirstOrDefaultAsync(x => x.Id == existingSubjectId, cancellationToken);
            if (subject != null)
            {
                subject.DisplayName = user.DisplayName;
                subject.UpdatedAt = now;
            }

            var fgaUser = await _context.Set<SqlOSFgaUser>().FirstOrDefaultAsync(x => x.SubjectId == existingSubjectId, cancellationToken);
            if (fgaUser != null)
            {
                fgaUser.Email = user.DefaultEmail;
                fgaUser.IsActive = user.IsActive;
            }

            return existingSubjectId;
        }

        await EnsureFgaSubjectTypeAsync("user", "User", cancellationToken);
        var newSubject = new SqlOSFgaSubject
        {
            Id = _cryptoService.GenerateId("subj"),
            SubjectTypeId = "user",
            DisplayName = user.DisplayName,
            OrganizationId = connection.OrganizationId,
            ExternalRef = user.Id,
            CreatedAt = now,
            UpdatedAt = now
        };
        var newUser = new SqlOSFgaUser
        {
            Id = _cryptoService.GenerateId("fusr"),
            SubjectId = newSubject.Id,
            Email = user.DefaultEmail,
            IsActive = user.IsActive
        };
        _context.Set<SqlOSFgaSubject>().Add(newSubject);
        _context.Set<SqlOSFgaUser>().Add(newUser);
        return newSubject.Id;
    }

    private async Task EnsureFgaSubjectTypeAsync(string id, string name, CancellationToken cancellationToken)
    {
        if (!await _context.Set<SqlOSFgaSubjectType>().AnyAsync(x => x.Id == id, cancellationToken))
        {
            _context.Set<SqlOSFgaSubjectType>().Add(new SqlOSFgaSubjectType
            {
                Id = id,
                Name = name
            });
        }
    }

    private async Task<string?> FindFgaSubjectIdForUserAsync(string connectionId, string userId, CancellationToken cancellationToken)
        => await _context.Set<SqlOSScimExternalId>()
            .Where(x => x.ConnectionId == connectionId && x.ResourceType == "User" && x.EntityId == userId)
            .Select(x => x.FgaSubjectId)
            .FirstOrDefaultAsync(cancellationToken)
        ?? await _context.Set<SqlOSFgaSubject>()
            .Where(x => x.SubjectTypeId == "user" && x.ExternalRef == userId)
            .Select(x => x.Id)
            .FirstOrDefaultAsync(cancellationToken);

    private async Task DeprovisionUserAccessAsync(SqlOSScimConnection connection, string userId, string? fgaSubjectId, CancellationToken cancellationToken)
    {
        var membership = await _context.Set<SqlOSMembership>()
            .FirstOrDefaultAsync(x => x.OrganizationId == connection.OrganizationId && x.UserId == userId, cancellationToken);
        if (membership != null)
        {
            membership.IsActive = false;
        }

        var sessions = await _context.Set<SqlOSSession>()
            .Where(x => x.OrganizationId == connection.OrganizationId && x.UserId == userId && x.RevokedAt == null)
            .ToListAsync(cancellationToken);
        foreach (var session in sessions)
        {
            session.RevokedAt = DateTime.UtcNow;
            session.RevocationReason = "scim_deprovisioned";
        }

        if (!string.IsNullOrWhiteSpace(fgaSubjectId))
        {
            var scimGroups = await _context.Set<SqlOSScimExternalId>()
                .Where(x => x.ConnectionId == connection.Id && x.ResourceType == "Group")
                .Select(x => x.EntityId)
                .ToListAsync(cancellationToken);
            var memberships = await _context.Set<SqlOSFgaUserGroupMembership>()
                .Where(x => x.SubjectId == fgaSubjectId && scimGroups.Contains(x.UserGroupId))
                .ToListAsync(cancellationToken);
            _context.Set<SqlOSFgaUserGroupMembership>().RemoveRange(memberships);
        }
    }

    private async Task ReplaceGroupMembersAsync(SqlOSScimConnection connection, SqlOSFgaUserGroup group, string groupExternalId, IReadOnlyList<string> memberValues, CancellationToken cancellationToken)
    {
        var desiredSubjectIds = new HashSet<string>(StringComparer.Ordinal);
        foreach (var value in memberValues)
        {
            var subjectId = await ResolveMemberSubjectIdAsync(connection.Id, value, cancellationToken);
            if (!string.IsNullOrWhiteSpace(subjectId))
            {
                desiredSubjectIds.Add(subjectId);
            }
        }

        var existing = await _context.Set<SqlOSFgaUserGroupMembership>()
            .Where(x => x.UserGroupId == group.Id)
            .ToListAsync(cancellationToken);
        var remove = existing.Where(x => !desiredSubjectIds.Contains(x.SubjectId)).ToList();
        _context.Set<SqlOSFgaUserGroupMembership>().RemoveRange(remove);
        foreach (var removed in remove)
        {
            var data = new { subjectId = removed.SubjectId, groupId = group.Id };
            await RecordSyncEventAsync(connection, "Group", group.Id, groupExternalId, "scim.group.member_removed", "success", null, data, cancellationToken);
            await RecordAuditAsync("scim.group.member_removed", connection.OrganizationId, "Group", group.Id, groupExternalId, data, cancellationToken);
        }

        var existingSubjectIds = existing.Select(x => x.SubjectId).ToHashSet(StringComparer.Ordinal);
        foreach (var subjectId in desiredSubjectIds.Where(subjectId => !existingSubjectIds.Contains(subjectId)))
        {
            _context.Set<SqlOSFgaUserGroupMembership>().Add(new SqlOSFgaUserGroupMembership
            {
                SubjectId = subjectId,
                UserGroupId = group.Id,
                CreatedAt = DateTime.UtcNow
            });
            var data = new { subjectId, groupId = group.Id };
            await RecordSyncEventAsync(connection, "Group", group.Id, groupExternalId, "scim.group.member_added", "success", null, data, cancellationToken);
            await RecordAuditAsync("scim.group.member_added", connection.OrganizationId, "Group", group.Id, groupExternalId, data, cancellationToken);
        }
    }

    private async Task<string?> ResolveMemberSubjectIdAsync(string connectionId, string value, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(value))
        {
            return null;
        }

        var trimmed = value.Trim();
        return await _context.Set<SqlOSScimExternalId>()
            .Where(x => x.ConnectionId == connectionId
                && x.ResourceType == "User"
                && x.IsActive
                && (x.EntityId == trimmed || x.ExternalId == trimmed))
            .Select(x => x.FgaSubjectId)
            .FirstOrDefaultAsync(cancellationToken);
    }

    private async Task<List<string>> GetCurrentScimGroupMembersAsync(string connectionId, string groupId, CancellationToken cancellationToken)
    {
        var subjectIds = await _context.Set<SqlOSFgaUserGroupMembership>()
            .Where(x => x.UserGroupId == groupId)
            .Select(x => x.SubjectId)
            .ToListAsync(cancellationToken);
        return await _context.Set<SqlOSScimExternalId>()
            .Where(x => x.ConnectionId == connectionId && x.ResourceType == "User" && x.FgaSubjectId != null && subjectIds.Contains(x.FgaSubjectId))
            .Select(x => x.EntityId)
            .ToListAsync(cancellationToken);
    }

    private async Task ApplyGroupMappingsAsync(SqlOSScimConnection connection, SqlOSFgaUserGroup group, string externalId, string displayName, CancellationToken cancellationToken)
    {
        var mappings = await _context.Set<SqlOSScimGroupMapping>()
            .Where(x => x.ConnectionId == connection.Id)
            .ToListAsync(cancellationToken);

        foreach (var mapping in mappings)
        {
            var resourceId = ResolveMappingResourceId(mapping, externalId, displayName);
            if (!mapping.IsEnabled || resourceId == null)
            {
                await RevokeManagedGrantAsync(connection, mapping.Id, externalId, cancellationToken);
                continue;
            }

            var role = await _context.Set<SqlOSFgaRole>()
                .FirstOrDefaultAsync(x => x.Key == mapping.RoleKey || x.Id == mapping.RoleKey, cancellationToken);
            var resource = await _context.Set<SqlOSFgaResource>()
                .FirstOrDefaultAsync(x => x.Id == resourceId, cancellationToken);
            if (role == null || resource == null)
            {
                var data = new { mappingId = mapping.Id, mapping.RoleKey, resourceId, error = "Mapped role or resource was not found." };
                await RecordSyncEventAsync(connection, "Group", group.Id, externalId, "scim.sync.failed", "failed", "Mapped role or resource was not found.", data, cancellationToken);
                await RecordAuditAsync("scim.sync.failed", connection.OrganizationId, "Group", group.Id, externalId, data, cancellationToken);
                continue;
            }

            var managed = await _context.Set<SqlOSScimManagedGrant>()
                .FirstOrDefaultAsync(x => x.ConnectionId == connection.Id
                    && x.MappingId == mapping.Id
                    && x.GroupExternalId == externalId
                    && x.ResourceId == resource.Id
                    && x.RoleId == role.Id
                    && x.RevokedAt == null, cancellationToken);
            if (managed != null)
            {
                continue;
            }

            var grant = new SqlOSFgaGrant
            {
                Id = _cryptoService.GenerateId("grant"),
                SubjectId = group.SubjectId,
                ResourceId = resource.Id,
                RoleId = role.Id,
                Description = string.IsNullOrWhiteSpace(mapping.Description)
                    ? $"SCIM mapping {mapping.Id}"
                    : mapping.Description,
                CreatedAt = DateTime.UtcNow
            };
            _context.Set<SqlOSFgaGrant>().Add(grant);
            _context.Set<SqlOSScimManagedGrant>().Add(new SqlOSScimManagedGrant
            {
                Id = _cryptoService.GenerateId("scgrant"),
                ConnectionId = connection.Id,
                MappingId = mapping.Id,
                GroupExternalId = externalId,
                FgaGroupId = group.Id,
                FgaGroupSubjectId = group.SubjectId,
                GrantId = grant.Id,
                RoleId = role.Id,
                ResourceId = resource.Id,
                CreatedAt = DateTime.UtcNow
            });
            await RecordSyncEventAsync(connection, "Group", group.Id, externalId, "scim.grant.mapped", "success", null, new { mappingId = mapping.Id, grantId = grant.Id, roleId = role.Id, resourceId = resource.Id }, cancellationToken);
            await RecordAuditAsync("scim.grant.mapped", connection.OrganizationId, "Group", group.Id, externalId, new { mappingId = mapping.Id, grantId = grant.Id, roleId = role.Id, resourceId = resource.Id }, cancellationToken);
        }
    }

    private static string? ResolveMappingResourceId(SqlOSScimGroupMapping mapping, string externalId, string displayName)
    {
        var match = mapping.MatchType switch
        {
            SqlOSScimGroupMappingMatchTypes.ExternalId => string.Equals(mapping.GroupExternalId, externalId, StringComparison.OrdinalIgnoreCase) ? new Dictionary<string, string>() : null,
            SqlOSScimGroupMappingMatchTypes.DisplayName => string.Equals(mapping.GroupDisplayName, displayName, StringComparison.OrdinalIgnoreCase) ? new Dictionary<string, string>() : null,
            SqlOSScimGroupMappingMatchTypes.Pattern => MatchPattern(mapping.GroupPattern, displayName),
            _ => null
        };
        if (match == null)
        {
            return null;
        }

        if (!string.IsNullOrWhiteSpace(mapping.ResourceId))
        {
            return mapping.ResourceId;
        }

        if (string.IsNullOrWhiteSpace(mapping.ResourceIdTemplate))
        {
            return null;
        }

        var resourceId = mapping.ResourceIdTemplate;
        foreach (var (key, value) in match)
        {
            resourceId = resourceId.Replace("{" + key + "}", value, StringComparison.Ordinal);
        }

        return resourceId;
    }

    private static Dictionary<string, string>? MatchPattern(string? pattern, string displayName)
    {
        if (string.IsNullOrWhiteSpace(pattern))
        {
            return null;
        }

        var match = Regex.Match(displayName, pattern, RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);
        if (!match.Success)
        {
            return null;
        }

        return match.Groups.Keys
            .Where(key => !int.TryParse(key, out _))
            .ToDictionary(key => key, key => match.Groups[key].Value, StringComparer.Ordinal);
    }

    private async Task RevokeManagedGrantAsync(SqlOSScimConnection connection, string mappingId, string groupExternalId, CancellationToken cancellationToken)
    {
        var grants = await _context.Set<SqlOSScimManagedGrant>()
            .Where(x => x.ConnectionId == connection.Id && x.MappingId == mappingId && x.GroupExternalId == groupExternalId && x.RevokedAt == null)
            .ToListAsync(cancellationToken);
        foreach (var managed in grants)
        {
            var grant = await _context.Set<SqlOSFgaGrant>().FirstOrDefaultAsync(x => x.Id == managed.GrantId, cancellationToken);
            if (grant != null)
            {
                _context.Set<SqlOSFgaGrant>().Remove(grant);
            }
            managed.RevokedAt = DateTime.UtcNow;
            var data = new { mappingId = managed.MappingId, grantId = managed.GrantId, roleId = managed.RoleId, resourceId = managed.ResourceId };
            await RecordSyncEventAsync(connection, "Group", managed.FgaGroupId, managed.GroupExternalId, "scim.grant.revoked", "success", null, data, cancellationToken);
            await RecordAuditAsync("scim.grant.revoked", connection.OrganizationId, "Group", managed.FgaGroupId, managed.GroupExternalId, data, cancellationToken);
        }
    }

    private async Task RevokeManagedGrantsForGroupAsync(SqlOSScimConnection connection, string groupExternalId, CancellationToken cancellationToken)
    {
        var grants = await _context.Set<SqlOSScimManagedGrant>()
            .Where(x => x.ConnectionId == connection.Id && x.GroupExternalId == groupExternalId && x.RevokedAt == null)
            .ToListAsync(cancellationToken);
        foreach (var managed in grants)
        {
            var grant = await _context.Set<SqlOSFgaGrant>().FirstOrDefaultAsync(x => x.Id == managed.GrantId, cancellationToken);
            if (grant != null)
            {
                _context.Set<SqlOSFgaGrant>().Remove(grant);
            }
            managed.RevokedAt = DateTime.UtcNow;
            var data = new { mappingId = managed.MappingId, grantId = managed.GrantId, roleId = managed.RoleId, resourceId = managed.ResourceId };
            await RecordSyncEventAsync(connection, "Group", managed.FgaGroupId, managed.GroupExternalId, "scim.grant.revoked", "success", null, data, cancellationToken);
            await RecordAuditAsync("scim.grant.revoked", connection.OrganizationId, "Group", managed.FgaGroupId, managed.GroupExternalId, data, cancellationToken);
        }
    }

    private async Task<SqlOSScimExternalId?> FindExternalLinkAsync(string connectionId, string resourceType, string externalId, CancellationToken cancellationToken)
        => await _context.Set<SqlOSScimExternalId>()
            .FirstOrDefaultAsync(x => x.ConnectionId == connectionId && x.ResourceType == resourceType && x.ExternalId == externalId, cancellationToken);

    private async Task UpsertExternalLinkAsync(string connectionId, string resourceType, string externalId, string entityId, string? fgaSubjectId, string? displayName, bool active, DateTime now, CancellationToken cancellationToken)
    {
        var link = await FindExternalLinkAsync(connectionId, resourceType, externalId, cancellationToken);
        if (link == null)
        {
            link = new SqlOSScimExternalId
            {
                Id = _cryptoService.GenerateId("scext"),
                ConnectionId = connectionId,
                ResourceType = resourceType,
                ExternalId = externalId,
                CreatedAt = now
            };
            _context.Set<SqlOSScimExternalId>().Add(link);
        }

        link.EntityId = entityId;
        link.FgaSubjectId = fgaSubjectId;
        link.DisplayName = displayName;
        link.IsActive = active;
        link.UpdatedAt = now;
        link.LastSyncedAt = now;
    }

    private async Task<JsonObject> ToScimUserAsync(SqlOSScimConnection connection, SqlOSUser user, CancellationToken cancellationToken)
    {
        var membership = await _context.Set<SqlOSMembership>()
            .AsNoTracking()
            .FirstOrDefaultAsync(x => x.OrganizationId == connection.OrganizationId && x.UserId == user.Id, cancellationToken);
        var link = await _context.Set<SqlOSScimExternalId>()
            .AsNoTracking()
            .FirstOrDefaultAsync(x => x.ConnectionId == connection.Id && x.ResourceType == "User" && x.EntityId == user.Id, cancellationToken);

        return new JsonObject
        {
            ["schemas"] = new JsonArray(UserSchema),
            ["id"] = user.Id,
            ["externalId"] = link?.ExternalId,
            ["userName"] = user.DefaultEmail ?? user.Id,
            ["displayName"] = user.DisplayName,
            ["active"] = user.IsActive && (membership?.IsActive ?? false),
            ["name"] = new JsonObject { ["formatted"] = user.DisplayName },
            ["emails"] = string.IsNullOrWhiteSpace(user.DefaultEmail)
                ? new JsonArray()
                : new JsonArray(new JsonObject { ["value"] = user.DefaultEmail, ["primary"] = true, ["type"] = "work" }),
            ["meta"] = new JsonObject
            {
                ["resourceType"] = "User",
                ["created"] = user.CreatedAt,
                ["lastModified"] = user.UpdatedAt
            }
        };
    }

    private async Task<JsonObject> ToScimGroupAsync(SqlOSScimConnection connection, string id, CancellationToken cancellationToken)
    {
        var group = await _context.Set<SqlOSFgaUserGroup>()
            .AsNoTracking()
            .FirstOrDefaultAsync(x => x.Id == id, cancellationToken)
            ?? throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM group not found.");
        var link = await _context.Set<SqlOSScimExternalId>()
            .AsNoTracking()
            .FirstOrDefaultAsync(x => x.ConnectionId == connection.Id && x.ResourceType == "Group" && x.EntityId == id && x.IsActive, cancellationToken)
            ?? throw new SqlOSScimException(StatusCodes.Status404NotFound, "SCIM group not found.");
        var memberships = await _context.Set<SqlOSFgaUserGroupMembership>()
            .AsNoTracking()
            .Where(x => x.UserGroupId == group.Id)
            .ToListAsync(cancellationToken);
        var subjectIds = memberships.Select(x => x.SubjectId).ToList();
        var userLinks = await _context.Set<SqlOSScimExternalId>()
            .AsNoTracking()
            .Where(x => x.ConnectionId == connection.Id && x.ResourceType == "User" && x.FgaSubjectId != null && subjectIds.Contains(x.FgaSubjectId))
            .ToListAsync(cancellationToken);

        return new JsonObject
        {
            ["schemas"] = new JsonArray(GroupSchema),
            ["id"] = group.Id,
            ["externalId"] = link.ExternalId,
            ["displayName"] = group.Name,
            ["members"] = new JsonArray(userLinks
                .Select(x => new JsonObject
                {
                    ["value"] = x.EntityId,
                    ["display"] = x.DisplayName
                })
                .ToArray<JsonNode?>()),
            ["meta"] = new JsonObject
            {
                ["resourceType"] = "Group",
                ["created"] = group.CreatedAt,
                ["lastModified"] = group.UpdatedAt
            }
        };
    }

    private async Task RecordSyncEventAsync(SqlOSScimConnection connection, string resourceType, string? resourceId, string? externalId, string action, string result, string? error, object? data, CancellationToken cancellationToken)
    {
        _context.Set<SqlOSScimSyncEvent>().Add(new SqlOSScimSyncEvent
        {
            Id = _cryptoService.GenerateId("scevt"),
            ConnectionId = connection.Id,
            OrganizationId = connection.OrganizationId,
            ResourceType = resourceType,
            ResourceId = resourceId,
            ExternalId = externalId,
            Action = action,
            Result = result,
            Error = error,
            DataJson = data == null ? null : JsonSerializer.Serialize(data, new JsonSerializerOptions(JsonSerializerDefaults.Web)),
            OccurredAt = DateTime.UtcNow
        });
    }

    private async Task RecordAuditAsync(string action, string organizationId, string resourceType, string? resourceId, string? externalId, object? data, CancellationToken cancellationToken)
    {
        var metadata = new Dictionary<string, object?>
        {
            ["resourceType"] = resourceType,
            ["resourceId"] = resourceId,
            ["externalId"] = externalId,
            ["payload"] = data
        };
        var audit = new SqlOSAuditLogService(_context, _cryptoService);
        await audit.RecordAsync(new SqlOSAuditLogRecordRequest(
            Action: action,
            OrganizationId: organizationId,
            Source: "scim",
            Actor: new SqlOSAuditActor("scim", externalId),
            Targets: string.IsNullOrWhiteSpace(resourceId) ? [] : [new SqlOSAuditTarget(resourceType.ToLowerInvariant(), resourceId)],
            Metadata: metadata), cancellationToken);
    }

    private static ScimUserRequest ParseUser(JsonObject payload)
    {
        var userName = ReadString(payload, "userName") ?? ReadPrimaryEmail(payload) ?? ReadString(payload, "externalId");
        if (string.IsNullOrWhiteSpace(userName))
        {
            throw new SqlOSScimException(StatusCodes.Status400BadRequest, "SCIM userName or primary email is required.", "invalidValue");
        }

        var displayName = ReadString(payload, "displayName")
            ?? payload["name"]?["formatted"]?.GetValue<string>()
            ?? userName;

        return new ScimUserRequest(
            userName.Trim(),
            ReadString(payload, "externalId"),
            ReadPrimaryEmail(payload) ?? userName.Trim(),
            displayName.Trim(),
            payload["active"]?.GetValue<bool>() ?? true);
    }

    private static ScimGroupRequest ParseGroup(JsonObject payload)
    {
        var displayName = ReadString(payload, "displayName");
        if (string.IsNullOrWhiteSpace(displayName))
        {
            throw new SqlOSScimException(StatusCodes.Status400BadRequest, "SCIM group displayName is required.", "invalidValue");
        }

        return new ScimGroupRequest(
            displayName.Trim(),
            ReadString(payload, "externalId"),
            ReadMemberValues(payload["members"]));
    }

    private static List<ScimPatchOperation> ReadOperations(JsonObject payload)
    {
        if (payload["Operations"] is not JsonArray operations)
        {
            throw new SqlOSScimException(StatusCodes.Status400BadRequest, "SCIM PATCH requires Operations.", "invalidSyntax");
        }

        return operations.OfType<JsonObject>()
            .Select(op => new ScimPatchOperation(
                ReadString(op, "op") ?? "replace",
                ReadString(op, "path"),
                op["value"]))
            .ToList();
    }

    private static List<string> ReadMemberValues(JsonNode? node)
    {
        if (node is not JsonArray array)
        {
            return [];
        }

        return array
            .OfType<JsonObject>()
            .Select(item => ReadString(item, "value"))
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value!.Trim())
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static string? ReadPrimaryEmail(JsonObject payload)
    {
        if (payload["emails"] is not JsonArray emails)
        {
            return null;
        }

        var objects = emails.OfType<JsonObject>().ToList();
        return objects.FirstOrDefault(x => x["primary"]?.GetValue<bool>() == true)?["value"]?.GetValue<string>()
            ?? objects.FirstOrDefault()?["value"]?.GetValue<string>();
    }

    private static string? ReadString(JsonObject payload, string propertyName)
        => payload.TryGetPropertyValue(propertyName, out var value) && value != null
            ? value.GetValue<string>()
            : null;

    private static string NormalizeScimExternalId(string? externalId, string fallback)
        => string.IsNullOrWhiteSpace(externalId) ? fallback.Trim() : externalId.Trim();

    private static string? TryReadEqFilter(string filter, string attribute)
    {
        var match = Regex.Match(filter, $"^{Regex.Escape(attribute)}\\s+eq\\s+\"(?<value>.+)\"$", RegexOptions.IgnoreCase);
        return match.Success ? match.Groups["value"].Value : null;
    }

    private static (int Skip, int Take, int StartIndex, int Count) ResolveScimPaging(int? startIndex, int? count)
    {
        var resolvedStart = Math.Max(1, startIndex ?? 1);
        var resolvedCount = Math.Clamp(count ?? 100, 1, 200);
        return (resolvedStart - 1, resolvedCount, resolvedStart, resolvedCount);
    }

    private static JsonObject ListResponse(JsonArray resources, int totalResults, int startIndex, int itemsPerPage)
        => new()
        {
            ["schemas"] = new JsonArray(ListResponseSchema),
            ["totalResults"] = totalResults,
            ["startIndex"] = startIndex,
            ["itemsPerPage"] = itemsPerPage,
            ["Resources"] = resources
        };

    private sealed record ScimUserRequest(string UserName, string? ExternalId, string? Email, string DisplayName, bool Active);
    private sealed record ScimGroupRequest(string DisplayName, string? ExternalId, IReadOnlyList<string> Members);
    private sealed record ScimPatchOperation(string Op, string? Path, JsonNode? Value);
}
