using System.Data.Common;
using System.Globalization;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql;
using SqlOS.Fga;
using SqlOS.Fga.Configuration;

namespace SqlOS.Database;

internal sealed partial class PostgreSqlDatabaseProvider : ISqlOSDatabaseProvider
{
    public static PostgreSqlDatabaseProvider Instance { get; } = new();

    public SqlOSDatabaseProviderKind Kind => SqlOSDatabaseProviderKind.PostgreSql;
    public string EfProviderName => SqlOSDatabase.PostgreSqlProviderName;
    public string DisplayName => "PostgreSQL";
    public string AuthMigrationResourcePrefix => "SqlOS.AuthServer.Schema.PostgreSql.";
    public string FgaMigrationResourcePrefix => "SqlOS.Fga.Schema.PostgreSql.";
    public string MaxStringStoreType => "text";

    public string QuoteIdentifier(string identifier)
        => "\"" + identifier.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";

    public string Qualify(string schema, string name)
        => $"{QuoteIdentifier(schema)}.{QuoteIdentifier(name)}";

    public string FilteredIndexIsNotNull(string column) => $"{QuoteIdentifier(column)} IS NOT NULL";
    public string FilteredIndexEqualsTrue(string column) => $"{QuoteIdentifier(column)} = TRUE";

    public IReadOnlyList<string> SplitBatches(string sql)
        => string.IsNullOrWhiteSpace(sql) ? [] : [sql];

    public DbParameter CreateParameter(string name, object? value)
        => new NpgsqlParameter(name, value ?? DBNull.Value);

    public string BuildEnsureAuthVersionTablesSql(string schema)
    {
        var quoted = QuoteIdentifier(schema);
        var versions = Qualify(schema, "SqlOSSchema");
        var applied = Qualify(schema, "SqlOSAppliedMigrations");
        return $"""
            CREATE SCHEMA IF NOT EXISTS {quoted};
            CREATE TABLE IF NOT EXISTS {versions} ("Version" INT NOT NULL);
            CREATE TABLE IF NOT EXISTS {applied} (
                "Sequence" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                "ScriptName" varchar(450) NOT NULL,
                "Version" INT NOT NULL,
                "AppliedAt" timestamp NOT NULL,
                CONSTRAINT "PK_SqlOSAppliedMigrations" PRIMARY KEY ("ScriptName"),
                CONSTRAINT "UX_SqlOSAppliedMigrations_Sequence" UNIQUE ("Sequence")
            );
            """;
    }

    public string BuildSelectVersionSql(string schema)
        => $"SELECT \"Version\" FROM {Qualify(schema, "SqlOSSchema")} LIMIT 1";

    public string BuildSelectAppliedMigrationsSql(string schema)
        => $"SELECT \"ScriptName\" FROM {Qualify(schema, "SqlOSAppliedMigrations")}";

    public string BuildRecordAppliedMigrationSql(string schema)
        => $"""
            INSERT INTO {Qualify(schema, "SqlOSAppliedMigrations")} ("ScriptName", "Version", "AppliedAt")
            SELECT @scriptName, @version, (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
            WHERE NOT EXISTS (
                SELECT 1 FROM {Qualify(schema, "SqlOSAppliedMigrations")} WHERE "ScriptName" = @scriptName);
            """;

    public string BuildUpdateVersionSql(string schema)
        => $"UPDATE {Qualify(schema, "SqlOSSchema")} SET \"Version\" = @targetVersion";

    public string BuildEnsureFgaVersionTableSql(string schema)
        => $"""
            CREATE SCHEMA IF NOT EXISTS {QuoteIdentifier(schema)};
            CREATE TABLE IF NOT EXISTS {Qualify(schema, "SqlOSFgaSchema")} ("Version" INT NOT NULL);
            """;

    public string BuildSelectFgaVersionSql(string schema)
        => $"SELECT \"Version\" FROM {Qualify(schema, "SqlOSFgaSchema")} LIMIT 1";

    public string BuildLockedSelectSql(string schema, string table, string whereSql, string? orderBySql = null)
    {
        var sql = $"SELECT * FROM {Qualify(schema, table)} WHERE {whereSql}";
        if (!string.IsNullOrWhiteSpace(orderBySql))
        {
            sql += $" ORDER BY {orderBySql}";
        }

        return sql + " FOR UPDATE";
    }

    /// <summary>
    /// <c>fn_IsResourceAccessible</c>: the point check over the lineage (see the SQL Server provider). The grant
    /// seek sits in a subquery with <c>OFFSET 0</c>, which PostgreSQL does not move conditions into, so it stays on
    /// <c>ResourceSubjectHash</c>. With the ids beside the hash, the grants-by-resource index looks as cheap to the
    /// planner (both estimates round to one row), and it may read every grant on the ancestor instead.
    /// </summary>
    public string BuildIsResourceAccessibleFunctionSql(SqlOSFgaOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        var schema = QuoteIdentifier(options.Schema);
        var tables = options.TableNames;
        var resources = Qualify(options.Schema, tables.Resources);
        var grants = Qualify(options.Schema, tables.Grants);
        var rolePermissions = Qualify(options.Schema, tables.RolePermissions);
        var permissions = Qualify(options.Schema, tables.Permissions);
        var levels = string.Join(", ", Enumerable.Range(0, SqlOSFgaLineage.Levels(options))
            .Select(level => $"({level.ToString(CultureInfo.InvariantCulture)}, x.{QuoteIdentifier(SqlOSFgaLineage.AncestorColumn(level))})"));
        // The result shape changed in 8.0 (it names the deciding grant), and CREATE OR REPLACE cannot change a
        // function's result type, so a function with the old shape is dropped first. Only that one: a drop
        // gives the function a new oid, and a query planned against the old one fails ("cache lookup failed
        // for function"), so the current shape is replaced in place while other sessions call it.
        var schemaLiteral = SqlLiteral(options.Schema);
        return $"""
            DO $sqlos_drop$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_proc p INNER JOIN pg_namespace n ON n.oid = p.pronamespace
                    WHERE n.nspname = '{schemaLiteral}' AND p.proname = 'fn_IsResourceAccessible'
                      AND pg_get_function_result(p.oid) NOT LIKE '%"GrantId"%')
                THEN
                    DROP FUNCTION {schema}."fn_IsResourceAccessible"(varchar, text, varchar);
                END IF;
            END
            $sqlos_drop$;
            CREATE OR REPLACE FUNCTION {schema}."fn_IsResourceAccessible"(
                p_resource_id varchar(450),
                p_subject_ids text,
                p_permission_id varchar(450)
            )
            RETURNS TABLE("Id" varchar(450), "GrantId" varchar(450), "SubjectId" varchar(450), "RoleId" varchar(450), "Level" integer)
            LANGUAGE sql
            STABLE
            AS $sqlos$
            SELECT a."Id", g."Id", g."SubjectId", g."RoleId", lv."Level"
            FROM {resources} x
            CROSS JOIN LATERAL (VALUES {levels}) AS lv("Level", "Seq")
            INNER JOIN {resources} a ON a."Seq" = lv."Seq"
            CROSS JOIN LATERAL unnest(ARRAY(SELECT live."SubjectId" FROM {schema}."fn_ActiveSubjects"(p_subject_ids) live)) AS s("SubjectId")
            CROSS JOIN LATERAL (
                SELECT g."Id", g."ResourceId", g."SubjectId", g."RoleId", g."EffectiveFrom", g."EffectiveTo"
                FROM {grants} g
                WHERE g."ResourceSubjectHash" = hashtextextended(a."Id", hashtextextended(s."SubjectId", 0))
                OFFSET 0
            ) g
            WHERE x."Id" = p_resource_id
              AND x."Reach" IS NOT NULL
              AND lv."Seq" IS NOT NULL
              AND lv."Level" >= x."Reach"
              AND EXISTS (
                  SELECT 1
                  FROM {permissions} permission
                  WHERE permission."Id" = p_permission_id
                    AND (permission."ResourceTypeId" IS NULL OR permission."ResourceTypeId" = x."ResourceTypeId")
              )
              -- Two pairs may share a hash: the ids decide.
              AND g."ResourceId" = a."Id"
              AND g."SubjectId" = s."SubjectId"
              AND g."RoleId" = ANY (ARRAY(SELECT rp."RoleId" FROM {rolePermissions} rp WHERE rp."PermissionId" = p_permission_id))
              AND (g."EffectiveFrom" IS NULL OR g."EffectiveFrom" <= (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))
              AND (g."EffectiveTo" IS NULL OR g."EffectiveTo" >= (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'))
            ORDER BY lv."Level" DESC
            LIMIT 1
            $sqlos$;
            """;
    }

    /// <summary>The point check as a query (see the SQL Server provider).</summary>
    public string BuildAccessMatchQuerySql(SqlOSFgaOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        return $"SELECT m.\"Id\", m.\"GrantId\", m.\"SubjectId\", m.\"RoleId\", m.\"Level\" FROM {QuoteIdentifier(options.Schema)}.\"fn_IsResourceAccessible\"({{0}}, {{1}}, {{2}}) AS m";
    }

    /// <summary>The query's first argument, as EF Core's FromSqlRaw numbers them.</summary>
    private const string ResourceIdArgument = "{0}";

    /// <summary>The path from the top of a resource's tree down to it, from its lineage (see the SQL Server provider).</summary>
    public string BuildResourcePathQuerySql(SqlOSFgaOptions options)
    {
        ArgumentNullException.ThrowIfNull(options);
        var resources = Qualify(options.Schema, options.TableNames.Resources);
        var levels = string.Join(", ", Enumerable.Range(0, SqlOSFgaLineage.Levels(options))
            .Select(level => $"({level.ToString(CultureInfo.InvariantCulture)}, x.{QuoteIdentifier(SqlOSFgaLineage.AncestorColumn(level))})"));
        return $"""
            SELECT lv."Level" AS "Level", a."Id" AS "ResourceId", a."Name" AS "Name", a."ResourceTypeId" AS "ResourceTypeId", a."IsActive" AS "IsActive",
                   (x."Reach" IS NOT NULL AND lv."Level" >= x."Reach") AS "InReach"
            FROM {resources} x
            CROSS JOIN LATERAL (VALUES {levels}) AS lv("Level", "Seq")
            INNER JOIN {resources} a ON a."Seq" = lv."Seq"
            WHERE x."Id" = {ResourceIdArgument}
            """;
    }

    public async Task AcquireTransactionLockAsync(
        DatabaseFacade database,
        string resource,
        TimeSpan timeout,
        string failureMessage,
        CancellationToken cancellationToken)
    {
        var timeoutMs = Math.Max(1, (int)timeout.TotalMilliseconds);
        try
        {
            await database.ExecuteSqlRawAsync(
                $"""
                SET LOCAL lock_timeout = '{timeoutMs}ms';
                SELECT pg_advisory_xact_lock(
                    ('x' || substr(md5(@resource), 1, 8))::bit(32)::int,
                    ('x' || substr(md5(@resource), 9, 8))::bit(32)::int);
                """,
                [CreateParameter("@resource", resource)],
                cancellationToken);
        }
        catch (Exception ex) when (ex is PostgresException { SqlState: PostgresErrorCodes.LockNotAvailable or "57014" })
        {
            throw new InvalidOperationException(failureMessage, ex);
        }
    }

    public async Task AcquireSessionLockAsync(
        DatabaseFacade database,
        string resource,
        TimeSpan timeout,
        string failureMessage,
        CancellationToken cancellationToken)
    {
        var timeoutMs = Math.Max(1, (int)timeout.TotalMilliseconds);
        try
        {
            await database.ExecuteSqlRawAsync(
                $"""
                SET lock_timeout = '{timeoutMs}ms';
                SELECT pg_advisory_lock(
                    ('x' || substr(md5(@resource), 1, 8))::bit(32)::int,
                    ('x' || substr(md5(@resource), 9, 8))::bit(32)::int);
                RESET lock_timeout;
                """,
                [CreateParameter("@resource", resource)],
                cancellationToken);
        }
        catch (Exception ex) when (ex is PostgresException { SqlState: PostgresErrorCodes.LockNotAvailable or "57014" })
        {
            throw new InvalidOperationException(failureMessage, ex);
        }
    }

    public Task ReleaseSessionLockAsync(DatabaseFacade database, string resource, CancellationToken cancellationToken)
        => database.ExecuteSqlRawAsync(
            """
            SELECT pg_advisory_unlock(
                ('x' || substr(md5(@resource), 1, 8))::bit(32)::int,
                ('x' || substr(md5(@resource), 9, 8))::bit(32)::int);
            """,
            [CreateParameter("@resource", resource)],
            cancellationToken);
}
